services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\Eventnews\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  GeorgRinger\Eventnews\EventListener\AfterFlexFormDataStructureParsedEventListener:
    tags: ['event.listener']

  GeorgRinger\Eventnews\EventListener\NewsImportPostHydrateEventListener:
    tags: ['event.listener']
